# Generated by Django 6.0 on 2026-01-07 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='books',
            new_name='number_of_books',
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_of_date',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(blank=True, choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.book'),
        ),
        migrations.AlterField(
            model_name='record',
            name='librarian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.librarian'),
        ),
        migrations.AlterField(
            model_name='record',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.student'),
        ),
        migrations.AlterField(
            model_name='record',
            name='take_off_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
