# Generated by Django 6.0 on 2026-01-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_books_student_number_of_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_of_date',
            field=models.DateField(),
        ),
    ]
