# Generated by Django 6.0 on 2026-01-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_author_birth_of_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='take_off_date',
            new_name='birth_off_date',
        ),
    ]
