# Generated by Django 6.0 on 2026-01-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_take_off_date_record_birth_off_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_of_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='time_of_work',
            field=models.TextField(blank=True, null=True),
        ),
    ]
